version: "3.7"

services:
  redis:
    image: "redis:6.2.1-alpine"
    container_name: "redis"
    restart: always
    command: redis-server --requirepass mypassword
    ports:
      - "6379:6379"

  rate-limit:
    image: "ratelimit"
    container_name: "ratelimit"
    restart: always
    ports:
      - "8080:8080"